//
//  main.cpp
//  A toyable language compiler (like a simple c++)

#include <iostream>
#include <TParser/TGrammar.h>

using namespace std;

void usage() 
{
    cout << "TParserGenerator inputFile outFile" << std::endl;
    cout << "inputFile: the grammar file" << std::endl;
    cout << "outFile: the parser file generated by TParserGenerator" << std::endl;
}

int main(int argc, char *argv[]) 
{
    if (argc != 2) {
        usage();
        return 0;
    }
    const string grammarFile = argv[0];
    
    TGrammar tgrammar;
    cout << "building parser using %s..." << grammarFile.c_str() << std::endl;
    buildGrammar(grammarFile, &tgrammar);    
    return 0;
}
